const productData = [
  {
    id: 0,
    title: "Apple MacBook Pro 14 Inch Space Grey",
    image: "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp",
    disCount: "-40%",
    price: "$120",
    originalPrice: "$160",
    rating: 4.5,
    reviews: 88,
  },
  {
    id: 1,
    title: "Asus Zenbook Pro Dual Screen Laptop",
    image: "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp",
    disCount: "-35%",
    price: "$960",
    originalPrice: "$1160",
    rating: 4,
    reviews: 75,
  },
  {
    id: 2,
    title: "IPS LCD Gaming Monitor",
    image: "https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/thumbnail.webp",
    disCount: "-30%",
    price: "$370",
    originalPrice: "$400",
    rating: 4.8,
    reviews: 99,
  },
  {
    id: 3,
    title: "Red Nail Polish",
    image: "https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp",
    disCount: "-25%",
    price: "$375",
    originalPrice: "$400",
    rating: 4.7,
    reviews: 99,
  },
  {
    id: 4,
    title: "Powder Canister",
    image: "https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp",
    disCount: "-50%",
    price: "$20",
    originalPrice: "$40",
    rating: 3,
    reviews: 89,
  },
  {
    id: 5,
    title: "Eyeshadow Palette with Mirror",
    image: "https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp",
    disCount: "-25%",
    price: "$75",
    originalPrice: "$100",
    rating: 2,
    reviews: 90,
  },
  {
    id: 6,
    title: "Essence Mascara Lash Princess",
    image: "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp",
    disCount: "-25%",
    price: "$75",
    originalPrice: "$100",
    rating: 4.7,
    reviews: 90,
  },
  {
    id: 7,
    title: "Red Lipstick",
    image: "https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp",
    disCount: "-25%",
    price: "$75",
    originalPrice: "$100",
    rating: 4.7,
    reviews: 90,
  },
];

export default productData;
